### ISSUE TITLE
Implement OKEx dealer bot

### ISSUE THREAD

**Issue by sebastienverreault** [GaloyMoney/galoy#265]
The current implementation for hedging USD balance uses FTX Perpetual Futures/Swap.
That strategy has a few documented drawbacks.
So we intend on implementing hedging using OKEx inverse futures.
Allowing for the using the most advantageous exchange/strategy, a composition of both, etc.

**Comment by nicolasburtey** [comment]
After thinking about it, I think one of the first task that should be done is refactoring the FTX module and splitting in 2 parts.

First we want to have a high level how much USD should be hedged/maintain. And also have some boundary to know whether it's necessary to buy/sell/hedge some USD. 

ie: we should have $1,000 in our books (we have a liability of $1,000 from the user of the wallet), but we already have $998, and so no action is really needed because our holding is in the boundary of +/- 1%.

now if we get a user balance of $1,200, then we need to buy USD, and we can execute some order. we will want to have multiple provider for the USD part. so we could have OkEx/FTX/Bitfinex, stable coin, or local "real" USD in a bank account as a provider. from an architecture standpoint, this part can be different because we can have different providers with different rules. 

So it's probably make sense to first start refactoring our backend in that sense.

**Comment by sebastienverreault** [comment]
All right re-orienting toward that split.
Will investigate the MongoDb watch for changes on USD balance, 
so notification would be sent and processed to assess need for re-hedging.
Alternatively query the database on a set sustainable rate (1x / 5sec?).

**Comment by nicolasburtey** [comment]
moved to its own repo
